name: 📄 Documentation
description: need to update documentation
labels: [documentation]

body:
  - type: textarea
    attributes:
      label: Something to tell?
      description: |
        anything
